name: Monitor Electoral Automático

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar Robot
        run: python bot_votos.py
